# config.py

TOKEN = 'MTI1MTU4NzM5NjgzMTU0MzMzNw.GOZCVo.B_BnR9L-7FQiomgz6BxmOJ-2TX2RI8x1jQ6g5g'
PREFIX = '?'
YOUTUBE_API_KEY = "AIzaSyCxS7zfyZ2OxZDacg4IbXBo1PAdaWChggI"
YOUTUBE_CHANNEL_ID = "UCDj4EDvpEy-O3PH54u_B3mg"